### ISSUE TITLE
Extract perflib to separate repo?

### ISSUE THREAD

**Issue by carlpett** [leoluk/perflib_exporter#15]
Hi!
Following some pretty long discussions, we've decided to loosen up the scope of wmi_exporter to not limit ourselves to just WMI. Would you be open to extracting perflib into its' own repo? Right now external consumers will pull in the application code as well when taking a dependency on perflib (due to Go dependency management). While not horrible as such, it is somewhat confusing, especially with the import paths.

**Comment by leoluk** [comment]
Glad to hear that! 

I'd rather keep perflib and perflib_exporter is a single repo, as most changes will require modifications to both the exporter and the library.

To my understanding, both dep and Go modules only pull in the actual dependencies of the code that is imported, so it will just ignore the exporter unless you import it.

I've added a v0.0.1 tag and a Go.mod file to make the library easier to consume.

**Comment by carlpett** [comment]
Right, that would be rather inconvenient on this end, good point. But thanks for adding the tag!
Are you interested in PRs for the perflib parts that add things that aren't directly necessary for the perflib_exporter? I'm experimenting a bit with how we'll consume it from the wmi_exporter, but so far a function for decoding a `PerfObject` to a slice of typed structs has been useful. Would be happy to upstream them if you think they'd fit the scope here.

**Comment by leoluk** [comment]
Absolutely, especially before the v1 release where we can still break the API.
