### ISSUE TITLE
IsBaseValue based on wrong constant?

### ISSUE THREAD

**Issue by carlpett** [leoluk/perflib_exporter#16]
In the parsing of `PerfCounterDef`, `IsBaseValue` is set like this:
https://github.com/leoluk/perflib_exporter/blob/e137d65289553940dff03f4bb83908c0acea069a/perflib/perflib.go#L340

Where is this constant taken from? In the sources I've found (for example [here](https://referencesource.microsoft.com/#System/compmod/microsoft/win32/NativeMethods.cs,742)), the constant used seems to be `PERF_DISPLAY_PERCENT`, while `PERF_COUNTER_BASE` is 0x00030000.

Are there multiple definitions of these constants, or is it wrong?

cc @bismarck

**Comment by bismarck** [comment]
@carlpett I believe it's wrong also.  Should be 0x000**3**0000.  For example, `PERF_SAMPLE_BASE` is 0x400**3**0401 and `PERF_RAW_BASE` is 400**3**0403.
