### ISSUE TITLE
Collect by object name rather than object ID

### ISSUE THREAD

**Issue by jwenz723** [leoluk/perflib_exporter#2]
Do you have any intention of adding functionality to handle doing collection based upon a set of object names rather than object id's?

For clarification:
Current:
`--perflib.objects=2`

Desired:
`--perflib.objects=System`

I pose this question because I have noticed with objects that are not created by the OS the id's differ from machine to machine, so there would be no way to create a set of object id's that could be consistent across all servers in my environment.

**Comment by leoluk** [comment]
I assumed that IDs were constant, sounds like that isn't always the case. Specifying objects by name sounds reasonable, even for static IDs.

Is there a publicly available example of a perflib provider which behaves like that?

**Comment by jwenz723** [comment]
At this point in time I don't have any examples, but I will update here if I can find one. Before 2 days ago, I had never heard of perflib. I was in the process of working on my own [prometheus exporter](https://github.com/jwenz723/pdh_exporter) that uses the PDH library, but now I am thinking your solution may be what I actually need.

I will have to do some research to see if there is a way to convert an object name into an object ID. If there isn't a way, then the alternative solution would be to do the same thing you are doing with your /dump endpoint at application startup and then store all the names/IDs in a map that can be used as a lookup table.

**Comment by leoluk** [comment]
Pretty sure that we have to enumerate them at runtime. We can probably just use the name table which we already have.

**Comment by jwenz723** [comment]
I created a possible solution to handle this. You can see my code in the following pull request: #3

**Comment by leoluk** [comment]
Fixed by jwenz723 in #3
