### ISSUE TITLE
prometheus/common dependency is out of date

### ISSUE THREAD

**Issue by breed808** [leoluk/perflib_exporter#32]
Version in use by this repository is v0.2.0, while the latest upstream version is v0.32.0.

However, the `github.com/prometheus/common/log` package was removed in v0.27.0, so this won't be a simple version change.

The [windows_exporter](https://github.com/prometheus-community/windows_exporter) project has copied the package to `github.com/prometheus-community/windows_exporter/log` which could be used as a drop-in replacement.

I'm happy to submit a PR for this if that makes things easier :smiley:

**Comment by leoluk** [comment]
#33 should fix this - please re-open if there's anything left to do!
