### ISSUE TITLE
Window agent not able to run after window update.

### ISSUE THREAD

**Issue by habitappaing** [leoluk/perflib_exporter#37]
When I try to run agent-windows-amd64.exe, I got this error. 

panic: ReqQueryValueEx failed: The system cannot find the file specified. errno 2                                                                                                                                                                   goroutine 1 [running]:                                                                                                    github.com/leoluk/perflib_exporter/perflib.QueryNameTable({0x4701c2d, 0xb})                                                       /go/pkg/mod/github.com/grafana/perflib_exporter@v0.1.1-0.20211013152516-e37e14fb8b0a/perflib/nametable.go:43 +0x257                                                                                                                         github.com/leoluk/perflib_exporter/perflib.init.0()                                                                               /go/pkg/mod/github.com/grafana/perflib_exporter@v0.1.1-0.20211013152516-e37e14fb8b0a/perflib/perflib.go:266 +0x29

**Comment by jefferbrecht** [comment]
@habitappaing, sorry to revive this, but were you able to resolve the error?
