### ISSUE TITLE
perflib_system_system_up_time_total vs \System\System Up Time value

### ISSUE THREAD

**Issue by rgl** [leoluk/perflib_exporter#6]
Using PowerShell (Windows 2016) `Get-Counter` gives this value:

```powershell
(Get-Counter '\System\System Up Time').CounterSamples

Path                               InstanceName  CookedValue
----                               ------------  -----------
\\prometheus\system\system up time              3073,1246154
```

But the same counter from perflib is returning a strange value of `131782376480315101` (maybe because this counter is of type ElapsedTime) from http://localhost:9432/dump?query=2:

| Name | Mangled name | Type | IsCounter | IsNsCtr | Value | Help Text |
|----------|---------------------|--------|---------------|------------|---------|--------------|
| [674] System Up Time |	system_up_time_total | 0x30240500 | true | false | 131782376480315101 |	System Up Time is the elapsed time (in seconds) that the computer has been running since it was last started. This counter displays the difference between the start time and the current time. |

From http://localhost:9432/metrics it returns:

```
# HELP perflib_system_system_up_time_total perflib metric: \\System(*)\\System Up Time (see /dump for docs) [674]
# TYPE perflib_system_system_up_time_total counter
perflib_system_system_up_time_total{name=""} 1.317823764803151e+17
```

**Comment by leoluk** [comment]
The raw value for `System Up Time` is the nanosecond boot timestamp:

```
PS C:\Users\Administrator> (Get-Counter '\System\System Up Time').CounterSamples[0] | Format-List *


Path             : \\win-go\system\system up time
InstanceName     :
CookedValue      : 17221644.4682943
RawValue         : 131610451718635980
SecondValue      : 131782668163318923
MultipleCount    : 1
CounterType      : ElapsedTime
Timestamp        : 8/9/2018 7:40:16 AM
Timestamp100NSec : 131782740163310000
Status           : 0
DefaultScale     : 4294967291
TimeBase         : 10000000
```

**Comment by rgl** [comment]
I'm not seeing a way to do the computation from PromQL, because perflib_system_system_up_time_total seems to be the RawValue (as obtained from Get-Counter cmdlet), which is the boot time (which is always a constant; what varies is SecondValue).

To compute the Up Time we need to use the formula described at [PERF_ELAPSED_TIME](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc756820%28v%3dws.10%29). In powershell this can be done with:

```powershell
$c = (Get-Counter '\System\System Up Time').CounterSamples[0]; [TimeSpan]::FromSeconds(($c.SecondValue-$c.RawValue)/$c.TimeBase)
```

Outputs:

```
Days              : 6
Hours             : 2
Minutes           : 36
Seconds           : 55
Milliseconds      : 879
Ticks             : 5278158790000
TotalDays         : 6,10898008101852
TotalHours        : 146,615521944444
TotalMinutes      : 8796,93131666667
TotalSeconds      : 527815,879
TotalMilliseconds : 527815879
```

Which is roughly the same as CookedValue (which will contain the number of seconds since boot):

```powershell
(Get-Counter '\System\System Up Time').CounterSamples[0] | Format-List *
```

Outputs:

```
Path             : \\prometheus\system\system up time
InstanceName     :
CookedValue      : 527817,4737885
RawValue         : 131777575424976830
SecondValue      : 131782853599714715
MultipleCount    : 1
CounterType      : ElapsedTime
Timestamp        : 09/08/2018 11:49:19
Timestamp100NSec : 131782889599710000
Status           : 0
DefaultScale     : 4294967291
TimeBase         : 10000000
```

So it seems that formula needs to be done by the perflib_exporter. Or is there another way?

I think its reasonable to normalize everything to seconds.

**Comment by BertHartm** [comment]
I don't recall if it directly applies to this counter, but I remember digging into this problem and finding that there was a constant computed by windows which felt like a bogomips (https://en.wikipedia.org/wiki/BogoMips) style value. That's factored into some of the raw counters, and so needs to be factored out. I couldn't find anything in what I was getting out of perflib that would directly or indirectly expose that value, so I was unable to actually calculate uptime.

I'll see if I can dig up some old notes on this (probably should have written it up at the time). I attempted to factor it out inside perflib, but couldn't get the numbers to work for some reason.

**Comment by rgl** [comment]
https://docs.microsoft.com/en-us/windows/desktop/perfctrs/calculating-counter-values seems to describe how to get a "display value" from raw values (some calculation even require two samples). Do you have something like that for PromQL? Or even a grafana dashboard?

**Comment by rgl** [comment]
I think I got it. Can you please confirm the following PromQL?

```
time()-(perflib_system_system_up_time_total/10000000-11644473600)
```

* `time()` returns the current time as the number of seconds after the unix epoch (`1970-01-01T00:00:00Z`).
* `perflib_system_system_up_time_total` is the time of when windows booted as the number of windows ticks after the windows epoch (`1601-01-01T00:00:00Z`).
* A windows tick is `1/10000000` seconds.
* Windows epoch is `11644473600` seconds behind unix epoch.

**Comment by leoluk** [comment]
Yup this sounds reasonable, nice find!

How about exposing an extra _epoch metric (and getting rid of _total)?

**Comment by rgl** [comment]
What would be the promql with that extra metric?

Do you have a grafana dashboard for perflib? That would be a great way to bring newcomers up to speed on how to use perflib_exporter

**Comment by leoluk** [comment]
That would be just `time()-perflib_system_system_up_time_epoch`.

perflib_exporter is very much a work in progress so no dashboard yet. Feel free to start making one!

**Comment by rgl** [comment]
Since it would be a synthetic metric, maybe call it `perflib_system_boot_time`?

I have one for wmi_exporter at https://github.com/rgl/prometheus-vagrant/blob/master/grafana-windows-dashboard.json but doing the same for perflib is proving to be a challenge, I'm currently stuck at https://github.com/leoluk/perflib_exporter/issues/8
